apiVersion: v1
kind: Service
metadata:
  name: microservicio-seguridad-service
  labels:
    name: microservicio-seguridad-service
    app: microservice
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: microservicio-seguridad
    type: microservice